### ISSUE TITLE
hust_wireless.py somewhat outdated?

### ISSUE THREAD

**Issue by Cra1gTucker** [recolic/awesome-hust#6]
不知为什么，最近（本学期以来？）校园网登录使用了RSA公钥加密密码，使用的JavaScript大概是这样
```
var key = new RSAKeyPair("10001","","9c2899b8ceddf9beafad2db8e431884a79fd9b9c881e459c0e1963984779d6612222cee814593cc458845bbba42b2d3474c10b9d31ed84f256c6e3a1c795e68e18585b84650076f122e763289a4bcb0de08762c3ceb591ec44d764a69817318fbce09d6ecb0364111f6f38e90dc44ca89745395a17483a778f1cc8dc990d87c3");
password = encryptedString(key, s);
```

然后post的时候加了一个`passwordEncrypt`参数

实践发现其实这玩意儿并不影响用之前的方式登录，不过也许按照目前校园网登录的方式会更好？（毕竟有加密）也许您可以考虑一下[我的repo](https://github.com/Cra1gTucker/hust-login)？

**Comment by recolic** [comment]
pull request pleaseOn Apr 10, 2019 07:55, Cra1gTucker <notifications@github.com> wrote:不知为什么，最近（本学期以来？）校园网登录使用了RSA公钥加密密码，使用的JavaScript大概是这样

var key = new RSAKeyPair("10001","","9c2899b8ceddf9beafad2db8e431884a79fd9b9c881e459c0e1963984779d6612222cee814593cc458845bbba42b2d3474c10b9d31ed84f256c6e3a1c795e68e18585b84650076f122e763289a4bcb0de08762c3ceb591ec44d764a69817318fbce09d6ecb0364111f6f38e90dc44ca89745395a17483a778f1cc8dc990d87c3");

password = encryptedString(key, s);



然后post的时候加了一个passwordEncrypt参数

实践发现其实这玩意儿并不影响用之前的方式登录，不过也许按照目前校园网登录的方式会更好？（毕竟有加密）也许您可以考虑一下我的repo？

**Comment by Cra1gTucker** [comment]
PRed! Thank you for your reply.

**Comment by recolic** [comment]
稍等。这种方法并不会增加安全性，因为它不能防止重放攻击。本质上就是多了个hash而已，原脚本不应该被标注outdated & insecure吧。

**Comment by Cra1gTucker** [comment]
对，因为是固定密钥又没有nonce，这个我们应该也没什么解决办法吧（只好看学校？），不过至少不能解出明文

**Comment by recolic** [comment]
其实这是个好消息，屁股决定脑袋，我们是受益者又不是受害者23333。close了。
